import "Core.WindowHandle.idl";

namespace DynamicDesktop.Core
{
    [bindable]
    [default_interface]
    unsealed runtimeclass WindowBackground
    {
        WindowHandle Handle { get; };
        overridable Boolean IsAvailable { get; };
        overridable Boolean IsEnabled { get; set; };

        overridable Windows.Foundation.Collections.IObservableMap<String, String> Details { get; };

        WindowBackground(WindowHandle handle);
    }
}
