namespace DynamicDesktop.Core
{
    runtimeclass WindowHandleWrapper : Windows.Foundation.IStringable
    {
        UInt64  HId         { get; };
        String  HexId       { get; };
        Boolean IsCovered   { get; };
        String  WindowTitle { get; };
        String  WindowClass { get; };
        UInt64  WindowIcon  { get; };

        WindowHandleWrapper(Int32 hId);
        WindowHandleWrapper(String name, Boolean isTitle);

        Boolean Cover();
        void Uncover();
        
        Boolean Valid();

        Boolean Equals(Object other);
    }
}
