import "Core.WindowBackground.idl";

namespace DynamicDesktop.Core
{
    [bindable]
    [default_interface]
    unsealed runtimeclass ApplicationBackground : WindowBackground
    {
        overridable WindowHandle Handle { get; };
        Windows.Foundation.Collections.IVectorView<WindowHandle> Handles { get; };

        Boolean IsProcessAvailable { get; };
        overridable Boolean IsAvailable { get; };

        ApplicationBackground(String commandline, String workingDir);

        Boolean Launch();
    }
}
