import "Core.WindowHandle.idl";

namespace DynamicDesktop.Core
{
    unsealed runtimeclass IBackgroundInfo
    {
        overridable WindowHandle Handle      { get; };
        overridable Boolean      IsAvailable { get; };
        overridable Windows.Foundation.Collections.IObservableMap<String, String> Details { get; };
    }

    runtimeclass WindowBackground : IBackgroundInfo
    {
        WindowHandle Handle { get; };

        WindowBackground(WindowHandle handle);
    }
}