import "Core.WindowHandle.idl";

namespace DynamicDesktop.Pages
{
    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        static Microsoft.UI.Xaml.DependencyProperty SelectedHandleProperty{ get; };

        Windows.Foundation.Collections.IObservableVector<DynamicDesktop.Core.WindowHandle> Handles{ get; };
        DynamicDesktop.Core.WindowHandle SelectedHandle{ get; set; };

        HomePage();

        Boolean AppendHandle(DynamicDesktop.Core.WindowHandle _handle);
        Boolean RemoveHandle(DynamicDesktop.Core.WindowHandle _handle);
    }
}
