import "Core.WindowHandleWrapper.idl";

namespace DynamicDesktop.Pages
{
    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        static Microsoft.UI.Xaml.DependencyProperty SelectedHandleProperty{ get; };

        Windows.Foundation.Collections.IObservableVector<DynamicDesktop.Core.WindowHandleWrapper> Handles{ get; };
        DynamicDesktop.Core.WindowHandleWrapper SelectedHandle{ get; set; };

        HomePage();

        Boolean AppendHandle(DynamicDesktop.Core.WindowHandleWrapper _handle);
        Boolean RemoveHandle(DynamicDesktop.Core.WindowHandleWrapper _handle);
    }
}
